# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1211615-rc/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7vx485tffg1761-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MEMORY_FILE {
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CLINT_Controller/rv32_clint.sv
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MPU/rv32_mpu.sv
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MPU/rv32_pmp_region.sv
    }
      rt::read_verilog -include /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MEMORY_FILE {
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/ADD.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/BPU/BTB_PLRU.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/BPU/Branch_Prediction_Unit.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/BPU/Branch_Target_Buff.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/COMPARE_1.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/CONVERT.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/Compare.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MEMORY_MACROS/DATA_MEMORY_1.2.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DEFINES/defines.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/DECODE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/DIV.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DTLB/DTLB.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/BPU/Direction_Predictor.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/EXCEPTION_UNIT/EXCEPTION_UNIT.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/EXECUTE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/FPU.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/FP_DECODE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/FP_EXECUTE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/FP_REG_FILE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/FP_to_FP.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/FP_to_int.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/IF_ID_EX.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/INST_FETCH.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/ITLB/ITLB.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/Crossbar/Interconnect.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/LZC.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MEMORY_MACROS/MEMORY_MACRO.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MEMORY_MACROS/MEMORY_MACRO_CACHE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/MULT.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/REG_FILE.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/BPU/Return_Addr_Stack.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/Rounding_Mode.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/SIGN_INJECTION.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/SQRT.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/Sys_counter.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/TRANSFER.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/IMEM_HIER/cachefsm.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DTLB/cam.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/cpu.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/CSR/csr.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DMEM_HIER/dcache_biu.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DMEM_HIER/dcache_dpram.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DMEM_HIER/dcache_ram_fsm.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DMEM_HIER/dcache_top.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/MEMORY_MACROS/dual_port_RAM.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/fet_dec_ex_mem.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/IMEM_HIER/icache.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/ITLB/icam.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/ITLB/ilru.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/int_to_FP.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/IMEM_HIER/interface_router.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/CSR/irq_bit_sync.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CPU/CSR/irq_pulser.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/DTLB/lru.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/IMEM_HIER/mem_hier.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/IP/or1200_amultp2_32x32.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/IP/or1200_fpu_div.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/CLINT_Controller/rv32_2dffsync.v
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/riscv_platform.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/IEEE_to_flopoco_DP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/IEEE_to_flopoco_SP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/add_DP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/add_SP.vhd
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/div_DP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/div_SP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/flopoco_to_IEEE_DP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/flopoco_to_IEEE_SP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/mul_DP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/mul_SP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/sqrt_DP.vhdl
      /home/rclab/FINAL_PROJECT/RV32G_Core/RV32G_Core/RTL/FPU/fpu/sqrt_SP.vhdl
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top riscv_platform
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1211615-rc/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
